### ISSUE TITLE
Find a free Travis CI solution

### ISSUE THREAD

**Issue by mikasonwar** [mikasonwar/homepage#10]
Find a free Travis CI solution, currently Travis is a paid platform, we are currently using a trial solution, but we need to find another solution soon.

**Comment by DipayanP007** [comment]
Hey I would like to work on this. I can migrate the project from travis ci to Github Actions. It will be free and fast.

**Comment by mikasonwar** [comment]
Hi @DipayanP007! Thanks for setting this up!

I'll approve the changes you did 😀
